GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "does this work",
  "important": false,
  "userId": "69e0fbc001e17d6e8c3a5345"
}


###
PUT http://localhost:3001/api/notes/2
Content-Type: application/json

{
  "content": "Browser can execute only JavaScript",
  "important": true,
}